config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root :to => "sessions#new"

  get '/test', to:"tests#test"
  #ROUTES FOR PROVIDER DASHBOARD
  get '/dashboard', to:"dashboard#main", as: "provider_dashboard"
  get '/sessions', to: "sessions#index"
  get '/my_profile', to: 'employees#show_current', as: 'employee_current'
  get '/edit_profile', to: 'employees#edit_current', as: 'employee_edit_current'
  patch '/my_profile', to: 'employees#update_current', as: 'employee_update_current'
  resources :employees
  resources :pumps, only: [:index, :show]
  resources :kiosks, only: [:index, :show]
  namespace :employee do
    get '', to: "sessions#new", as: 'signin'
    get '/signout', to: 'sessions#destroy', as: 'signout' #get rather than delete bc of issue with twitter bootstrap link_to
    resources :sessions, only: [:new, :create, :destroy]
  end

  #ROUTES FOR ADMIN DASHBOARD
  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    get '/', to: "sessions#new", as: 'signin'
    get '/add_hub', to: 'hubs#new', as: 'add_new_hub'
    get '/signout', to: 'sessions#destroy', as: 'signout' #get rather than delete bc of issue with twitter bootstrap link_to
    get '/dashboard', to:'dashboard#main', as: 'dashboard'
    get '/operations', to:'operations#index', as: 'operations'
    get '/my_profile', to: 'admins#show_current', as: 'current'
    get '/edit_profile', to: 'admins#edit_current', as: 'edit_current'
    patch '/my_profile', to: 'admins#update_current', as: 'update_current'
  #ROUTES FOR AJAX REQUESTS
    get "/credits_by_kiosk", to: "transactions#credits_by_kiosk"

    resources :kiosks
    resources :pumps
    resources :hubs
    resources :employees
    resources :admins
    resources :providers do
      resources :pumps, :kiosks, :employees
    end
    #ROUTES FOR AJAX REQUESTS
    get "/credits_by_kiosk", to: "transactions#credits_by_kiosk"
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  include PerspectiveSummary
  layout "admin_application"
  before_filter :require_admin_signin

  def main
    @sms = sms_balance_by_pump_table
    @total_credits_sold = credits_by_kiosk_for_all_table
    @total_water = dispensed_by_pump_for_all_table(true)
    @shopkeepers_credit = credits_remaining_by_kiosk_table
    @credits_bought = credits_bought_by_kiosk(true)
    js :viz_data => [credits_by_kiosk_by_month, credits_bought_by_kiosk,credits_remaining_by_kiosk, dispensed_by_pump_by_month, errors_by_hub_chart, getHubs]
    @new_hubs_ids = (Transaction.all - Hub.get_all_transactions).map { |transaction| transaction.location_id }.uniq
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include PerspectiveSummary
  layout "provider_application"
  before_filter :require_employee_signin

  def main
    js :viz_data => [dispensed_by_pump_for_provider(current_provider), credits_by_kiosk_for_provider(current_provider), getHubs]
    render "dashboard/main"
  end
end

app/views/dashboard/_dropdown_new.haml
%li
  = link_to '<i class="fa fa-user fa-fw"></i> Employee'.html_safe, new_employee_path

app/views/dashboard/_map.haml
#map

app/views/dashboard/_side_menu.haml
%li
	=link_to '<i class="fa fa-dashboard fa-fw"></i> Dashboard'.html_safe, root_path

%li
	=link_to '<i class="fa fa-tint fa-fw"></i> Water Pumps'.html_safe, pumps_path

%li
	=link_to '<i class="fa fa-home fa-fw"></i> Water Kiosks'.html_safe, kiosks_path

%li
	=link_to '<i class="fa fa-user fa-fw"></i> Manage Employees'.html_safe, employees_path

app/views/dashboard/login.haml
.container
  .row
    .col-md-4.col-md-offset-4
      .login-panel.panel.panel-default
        .panel-heading
          %h3.panel-title Water Provider Signin
        .panel-body
          %form{:role => "form"}
            %fieldset
              .form-group
                %input.form-control{:autofocus => "", :name => "email", :placeholder => "E-mail", :type => "email"}
              .form-group
                %input.form-control{:name => "password", :placeholder => "Password", :type => "password", :value => ""}
              .checkbox
                %label
                  %input{:name => "remember", :type => "checkbox", :value => "Remember Me"}
                    Remember Me
              / Change this to a button or input when using this as a form
              %a.btn.btn-lg.btn-success.btn-block= link_to 'Login', provider_dashboard_path

app/views/dashboard/main.haml
.col-lg-12
  %h1.page-header
    = current_provider.name
    %small - Provider
    .panel.panel-default.mt20
      .panel-body
        #chart-container
.col-lg-12
  %h3.pull-left Water Pumps
  .pull-right
  .table-responsive
    %table.table.table-striped.table-bordered.table-hover.mt20
      %thead
        %tr
          %th Location ID
          %th Name
          %th Longitude
          %th Latitude
          %th Status code
          %th
      %tbody
        - current_provider.pumps.each do |pump|
          %tr
            %td= pump.location_id
            %td= link_to pump.name, pump_path(pump)
            %td= pump.longitude
            %td= pump.latitude
            %td= pump.status_code
.col-lg-12
  %h3.pull-left Kiosks
  .table-responsive
    %table.table.table-striped.table-bordered.table-hover.mt20.mb20
      %thead
        %tr
          %th Location ID
          %th Name
          %th Longitude
          %th Latitude
          %th Status code
          %th
      %tbody
        - current_provider.kiosks.each do |kiosk|
          %tr
            %td= kiosk.location_id
            %td= link_to kiosk.name, kiosk_path(kiosk)
            %td= kiosk.longitude
            %td= kiosk.latitude
            %td= kiosk.status_code
.col-lg-12
  %h3.pull-left Employees
  .pull-right
    = button_to "New Employee", new_employee_path, method: "get", class: "btn btn-primary btn-xs mt20"
  .table-responsive
    %table.table.table-striped.table-bordered.table-hover.mt20
      %thead
        %tr
          %th Name
          %th Email
          %th Phone Number
          %th
      %tbody
        - current_provider.employees.each do |employee|
          %tr
            %td= employee.name
            %td= employee.email
            %td= employee.phone_number
            %td
              = link_to '<i class="fa fa-trash fa-fw"></i>'.html_safe, employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' }
              = link_to '<i class="fa fa-pencil fa-fw"></i>'.html_safe, edit_employee_path(employee)
.row
.col-lg-12
  .panel.panel-default
    .panel-heading
      %i.fa.fa-map-marker.fa-fw
      Water pumps and kiosks
      .pull-right
        .minimize.map-button
          %i.fa.fa-minus.fa-fw
    .panel-body
      #map