config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root :to => "sessions#new"

  get '/test', to:"tests#test"
  #ROUTES FOR PROVIDER DASHBOARD
  get '/dashboard', to:"dashboard#main", as: "provider_dashboard"
  get '/sessions', to: "sessions#index"
  get '/my_profile', to: 'employees#show_current', as: 'employee_current'
  get '/edit_profile', to: 'employees#edit_current', as: 'employee_edit_current'
  patch '/my_profile', to: 'employees#update_current', as: 'employee_update_current'
  resources :employees
  resources :pumps, only: [:index, :show]
  resources :kiosks, only: [:index, :show]
  namespace :employee do
    get '', to: "sessions#new", as: 'signin'
    get '/signout', to: 'sessions#destroy', as: 'signout' #get rather than delete bc of issue with twitter bootstrap link_to
    resources :sessions, only: [:new, :create, :destroy]
  end

  #ROUTES FOR ADMIN DASHBOARD
  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    get '/', to: "sessions#new", as: 'signin'
    get '/add_hub', to: 'hubs#new', as: 'add_new_hub'
    get '/signout', to: 'sessions#destroy', as: 'signout' #get rather than delete bc of issue with twitter bootstrap link_to
    get '/dashboard', to:'dashboard#main', as: 'dashboard'
    get '/operations', to:'operations#index', as: 'operations'
    get '/my_profile', to: 'admins#show_current', as: 'current'
    get '/edit_profile', to: 'admins#edit_current', as: 'edit_current'
    patch '/my_profile', to: 'admins#update_current', as: 'update_current'
  #ROUTES FOR AJAX REQUESTS
    get "/credits_by_kiosk", to: "transactions#credits_by_kiosk"

    resources :kiosks
    resources :pumps
    resources :hubs
    resources :employees
    resources :admins
    resources :providers do
      resources :pumps, :kiosks, :employees
    end
    #ROUTES FOR AJAX REQUESTS
    get "/credits_by_kiosk", to: "transactions#credits_by_kiosk"
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  include PerspectiveSummary
  layout "admin_application"
  before_filter :require_admin_signin

  def main
    @sms = sms_balance_by_pump_table
    @total_credits_sold = credits_by_kiosk_for_all_table
    @total_water = dispensed_by_pump_for_all_table(true)
    @shopkeepers_credit = credits_remaining_by_kiosk_table
    @credits_bought = credits_bought_by_kiosk(true)
    js :viz_data => [credits_by_kiosk_by_month, credits_bought_by_kiosk,credits_remaining_by_kiosk, dispensed_by_pump_by_month, errors_by_hub_chart, getHubs]
    @new_hubs_ids = (Transaction.all - Hub.get_all_transactions).map { |transaction| transaction.location_id }.uniq
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include PerspectiveSummary
  layout "provider_application"
  before_filter :require_employee_signin

  def main
    js :viz_data => [dispensed_by_pump_for_provider(current_provider), credits_by_kiosk_for_provider(current_provider), getHubs]
    render "dashboard/main"
  end
end

app/views/admin/dashboard/_dropdown_new.haml
%li
	= link_to '<i class="fa fa-building-o fa-fw"></i> Provider'.html_safe, new_admin_provider_path
%li.divider
%li
	= link_to '<i class="fa fa-user fa-fw"></i> Provider Employee'.html_safe, new_admin_employee_path
%li.divider
%li
	= link_to '<i class="fa fa-tint fa-fw"></i> Water Pump'.html_safe, new_admin_pump_path
%li.divider
%li
	= link_to '<i class="fa fa-home fa-fw"></i> Water Kiosk'.html_safe, new_admin_kiosk_path
%li.divider
%li
	= link_to '<i class="fa fa-gear fa-fw"></i> Admin Account'.html_safe, new_admin_admin_path

app/views/admin/dashboard/_side_menu.haml
%li{:class => "#{'active' if params[:controller] == 'admin/dashboard'}"}
	=link_to '<i class="fa fa-dashboard fa-fw"></i> Dashboard'.html_safe, admin_dashboard_path
%li{:class => "#{'active' if params[:controller] == 'admin/providers'}"}
	=link_to '<i class="fa fa-building-o fa-fw"></i> Providers'.html_safe, admin_providers_path
%li{:class => "#{'active' if params[:controller] == 'admin/employees'}"}
	=link_to '<i class="fa fa-user fa-fw"></i> Provider Employees'.html_safe, admin_employees_path
%li{:class => "#{'active' if params[:controller] == 'admin/pumps'}"}
	=link_to '<i class="fa fa-tint fa-fw"></i> Water Pumps'.html_safe, admin_pumps_path
%li{:class => "#{'active' if params[:controller] == 'admin/kiosks'}"}
	=link_to '<i class="fa fa-home fa-fw"></i> Water Kiosks'.html_safe, admin_kiosks_path
%li{:class => "#{'active' if params[:controller] == 'admin/operations'}"}
	=link_to '<i class="fa fa-gear fa-fw"></i> Operations'.html_safe, admin_operations_path

app/views/admin/dashboard/login.haml
.container
  .row
    .col-md-4.col-md-offset-4
      .login-panel.panel.panel-default
        .panel-heading
          %h3.panel-title Admin Signin
        .panel-body
          %form{:role => "form"}
            %fieldset
              .form-group
                %input.form-control{:autofocus => "", :name => "email", :placeholder => "E-mail", :type => "email"}
              .form-group
                %input.form-control{:name => "password", :placeholder => "Password", :type => "password", :value => ""}
              .checkbox
                %label
                  %input{:name => "remember", :type => "checkbox", :value => "Remember Me"}
                    Remember Me
              / Change this to a button or input when using this as a form
              %a.btn.btn-lg.btn-success.btn-block= link_to 'Login', admin_dashboard_path

app/views/admin/dashboard/main.haml
.col-lg-12
  %h1.page-header Susteq Dashboard
  .panel.panel-default.mt20
    .panel-heading
    .panel-body
      #chart-container
.col-lg-12
  %h3 Credits Bought by Kiosk
  .table-responsive
    %table#dataTables-example.table.table-striped.table-bordered.table-hover.mt20
      %thead
        %tr
          %th Kiosk Location Id
          %th Credits bought
      %tbody
        - @credits_bought.each do |kiosk|
          %tr
            %td= kiosk[:label]
            %td= kiosk[:value]
.col-lg-12
  %h3 SMS low
  .table-responsive
    %table#dataTables-example.table.table-striped.table-bordered.table-hover.mt20
      %thead
        %tr
          %th Hub
          %th request date
          %th Amount
      %tbody
        - @sms.each do |sms|
          %tr
            %td= sms[:location_id]
            %td= sms[:date]
            %td= sms[:total]
.col-lg-12
  %h3 Total Water Dispensed by Water Point
  .table-responsive
    %table#dataTables-example.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th Water Point
          %th Litres
      %tbody
        - @total_water.each do |hub|
          %tr
            %td= hub[:label]
            %td= hub[:value]
.col-lg-12
  %h3 Shopkeepers credit
  .table-responsive
    %table#dataTables-example.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th Hub
          %th Date
          %th Credits
      %tbody
        - @shopkeepers_credit.each do |hub|
          %tr
            %td= hub[:label]
            %td= hub[:date]
            %td= hub[:value]
.col-lg-12
  .panel.panel-default
    .panel-heading
      %i.fa.fa-map-marker.fa-fw
      Water points and kiosks
      .pull-right
        .minimize.map-button
          %i.fa.fa-minus.fa-fw
    .panel-body#map


- unless @new_hubs_ids.empty?
  %h3 Hubs with the following location ids have not yet been added to the Hubs table:
  .table-responsive
    %table#dataTables-example.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th Hub
      %tbody
        - @new_hubs_ids.each do |id|
          %tr
            %td= link_to id, admin_add_new_hub_path(new_hubs_id: id)