config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root :to => "sessions#new"

  get '/test', to:"tests#test"
  #ROUTES FOR PROVIDER DASHBOARD
  get '/dashboard', to:"dashboard#main", as: "provider_dashboard"
  get '/sessions', to: "sessions#index"
  get '/my_profile', to: 'employees#show_current', as: 'employee_current'
  get '/edit_profile', to: 'employees#edit_current', as: 'employee_edit_current'
  patch '/my_profile', to: 'employees#update_current', as: 'employee_update_current'
  resources :employees
  resources :pumps, only: [:index, :show]
  resources :kiosks, only: [:index, :show]
  namespace :employee do
    get '', to: "sessions#new", as: 'signin'
    get '/signout', to: 'sessions#destroy', as: 'signout' #get rather than delete bc of issue with twitter bootstrap link_to
    resources :sessions, only: [:new, :create, :destroy]
  end

  #ROUTES FOR ADMIN DASHBOARD
  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    get '/', to: "sessions#new", as: 'signin'
    get '/add_hub', to: 'hubs#new', as: 'add_new_hub'
    get '/signout', to: 'sessions#destroy', as: 'signout' #get rather than delete bc of issue with twitter bootstrap link_to
    get '/dashboard', to:'dashboard#main', as: 'dashboard'
    get '/operations', to:'operations#index', as: 'operations'
    get '/my_profile', to: 'admins#show_current', as: 'current'
    get '/edit_profile', to: 'admins#edit_current', as: 'edit_current'
    patch '/my_profile', to: 'admins#update_current', as: 'update_current'
  #ROUTES FOR AJAX REQUESTS
    get "/credits_by_kiosk", to: "transactions#credits_by_kiosk"

    resources :kiosks
    resources :pumps
    resources :hubs
    resources :employees
    resources :admins
    resources :providers do
      resources :pumps, :kiosks, :employees
    end
    #ROUTES FOR AJAX REQUESTS
    get "/credits_by_kiosk", to: "transactions#credits_by_kiosk"
  end

end

app/views/admin/admins/_form.haml
= form_for [:admin, @admin] do |f|
	- if flash.any?
		%h4{:style => "font-weight:bold;color:red;"}
			Admin not saved:
		%ul
			- flash[:error_messages].each do |msg|
				%li{:style => "font-weight:bold;color:red;"}= msg
	.form-group
		= f.label :name
		%br
		= f.text_field :name, class: "form-control"
	.form-group
		= f.label :email
		%br
		= f.text_field :email, class: "form-control"
	.form-group
		= f.label :phone_number
		%br
		= f.text_field :phone_number, class: "form-control"
	.form-group
		= f.label :password
		%br
		= f.text_field :password, class: "form-control", placeholder:"**********"
	.actions
		= f.submit class: "btn btn-default"

app/views/admin/admins/_list.haml
.table-responsive
  %table#dataTables-example.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Email
        %th Phone Number
        %th Created On
        %th
    %tbody
      - @admins.each_with_index do |admin, index|
        - index % 2 == 0 ? classes = ["odd","gradeX"] : classes = ["even","gradeC"]
        %tr{:class => classes}
          %td= admin.name
          %td= admin.email
          %td= admin.phone_number
          %td= admin.created_at.strftime('%c')
          %td
            = link_to '<i class="fa fa-trash fa-fw"></i>'.html_safe, admin_admin_path(admin), method: :delete, data: { confirm: 'Are you sure?' }
            = link_to '<i class="fa fa-pencil fa-fw"></i>'.html_safe, edit_admin_admin_path(admin)

app/views/admin/admins/edit.haml
.row
.col-lg-12
	%h1.page-header Edit Admin Profile
%hr
.col-lg-6
	= render 'form'

app/views/admin/admins/edit_current.haml
.row
	.col-lg-12
		%h1.page-header Edit My Profile
= form_for current_admin, url: {action:"update_current"} do |f|
	- if flash.any?
		%h4{:style => "font-weight:bold;color:red;"}
			Your profile not saved:
		%ul
			- flash[:error_messages].each do |msg|
				%li{:style => "font-weight:bold;color:red;"}= msg
	.form-group
		= f.label :name
		%br
		= f.text_field :name, class: "form-control", value: current_admin.name
	.form-group
		= f.label :email
		%br
		= f.text_field :email, class: "form-control", value: current_admin.email
	.form-group
		= f.label :phone_number
		%br
		= f.text_field :phone_number, class: "form-control", value: current_admin.phone_number
	.form-group
		= f.label :password
		%br
		= f.text_field :password, class: "form-control", placeholder: "***********"
	.actions
		= f.submit class: "btn btn-default"

app/views/admin/admins/index.haml
.row
.col-lg-12
	%h1.page-header Admin Profiles
	= link_to '<button class="btn btn-primary btn-md pull-right btn-add" type="button"><i class="fa fa-plus fa-fw"></i>Add Admin</button>'.html_safe, new_admin_admin_path
%hr
.col-lg-12.mt20
	= render 'list'

app/views/admin/admins/new.haml
.row
.col-lg-12
	%h1.page-header New Admin
%hr
.col-lg-6
	= render 'form'

app/views/admin/admins/show.haml
.container
  .row
    .col-sm-10
      %h1 Admin Profile
  .row
    .col-sm-6
      / left col
      %ul.list-group
        %li.list-group-item.text-muted Account Details
        %li.list-group-item.text-right
          %span.pull-left
            %strong Name
          = @admin.name
        %li.list-group-item.text-right
          %span.pull-left
            %strong Email
          = @admin.email
        %li.list-group-item.text-right
          %span.pull-left
            %strong Profile Created
          = @admin.created_at.strftime('%c')

    = link_to '<i class="fa fa-trash fa-fw"></i>'.html_safe, admin_admin_path(@admin), method: :delete, data: { confirm: 'Are you sure?' }
    = link_to '<i class="fa fa-pencil fa-fw"></i>'.html_safe, edit_admin_admin_path(@admin)

app/views/admin/admins/show_current.haml
.row
.col-lg-12
  %h1.page-header
    My Admin Profile
.col-lg-12
  %h3.pull-left Account Details
  %p.pull-right.mt20
    = link_to '<i class="fa fa-pencil fa-fw"></i>'.html_safe, admin_edit_current_path
.col-lg-6
  %table.gen-info
    %col.col-lg-5
    %tr
      %th Name
      %td= current_admin.name
    %tr
      %th Email
      %td= current_admin.email
    %tr
      %th Phone number
      %td= current_admin.phone_number
    %tr
      %th Created at
      %td= current_admin.created_at.strftime('%c')