config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root :to => "sessions#new"

  get '/test', to:"tests#test"
  #ROUTES FOR PROVIDER DASHBOARD
  get '/dashboard', to:"dashboard#main", as: "provider_dashboard"
  get '/sessions', to: "sessions#index"
  get '/my_profile', to: 'employees#show_current', as: 'employee_current'
  get '/edit_profile', to: 'employees#edit_current', as: 'employee_edit_current'
  patch '/my_profile', to: 'employees#update_current', as: 'employee_update_current'
  resources :employees
  resources :pumps, only: [:index, :show]
  resources :kiosks, only: [:index, :show]
  namespace :employee do
    get '', to: "sessions#new", as: 'signin'
    get '/signout', to: 'sessions#destroy', as: 'signout' #get rather than delete bc of issue with twitter bootstrap link_to
    resources :sessions, only: [:new, :create, :destroy]
  end

  #ROUTES FOR ADMIN DASHBOARD
  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    get '/', to: "sessions#new", as: 'signin'
    get '/add_hub', to: 'hubs#new', as: 'add_new_hub'
    get '/signout', to: 'sessions#destroy', as: 'signout' #get rather than delete bc of issue with twitter bootstrap link_to
    get '/dashboard', to:'dashboard#main', as: 'dashboard'
    get '/operations', to:'operations#index', as: 'operations'
    get '/my_profile', to: 'admins#show_current', as: 'current'
    get '/edit_profile', to: 'admins#edit_current', as: 'edit_current'
    patch '/my_profile', to: 'admins#update_current', as: 'update_current'
  #ROUTES FOR AJAX REQUESTS
    get "/credits_by_kiosk", to: "transactions#credits_by_kiosk"

    resources :kiosks
    resources :pumps
    resources :hubs
    resources :employees
    resources :admins
    resources :providers do
      resources :pumps, :kiosks, :employees
    end
    #ROUTES FOR AJAX REQUESTS
    get "/credits_by_kiosk", to: "transactions#credits_by_kiosk"
  end

end

app/models/pump.rb
class Pump < Hub
  belongs_to :provider
  has_many :transactions, as: :transactable

  def water_dispensed
    water_sum = 0
    dispenses = transactions.where(transaction_code: 1)
    dispenses.each {|s| water_sum += s.amount}
    water_sum
  end

  def provider
    super || NullProvider.new
  end
end

app/controllers/admin/pumps_controller.rb
class Admin::PumpsController < ApplicationController
  include PerspectiveSummary
  layout "admin_application"
  before_filter :require_admin_signin

  def new
    @pump = Pump.new
    @providers = Provider.all
  end

  def show
    @pump = Pump.find params[:id]
    js :viz_data => [dispensed_by_month(@pump), getHubs]
  end

  def create
    if params[:provider_id]
      begin
      @provider = Provider.find(params[:provider_id])
      @pump = Pump.create!(pump_params)
      redirect_to admin_provider_path(@provider)
      rescue ActiveRecord::RecordInvalid => invalid
        flash[:error_messages] = invalid.record.errors.full_messages
        redirect_to new_admin_provider_pump_path(@provider)
      end
    else
      begin
      @pump = Pump.create!(pump_params)
      redirect_to admin_pumps_path
      rescue ActiveRecord::RecordInvalid => invalid
        flash[:error_messages] = invalid.record.errors.full_messages
        redirect_to new_admin_pump_path
      end
    end
  end

  def index
    @pumps = Pump.all
    js :viz_data => [dispensed_by_pump_for_all_table(false), getHubs]
  end

  def edit
    @pump = Pump.find params[:id]
  end

  def update #MLM NOTES TO REFACTOR - Need different way to redirect user when approach from nested provider route vs top level route
    @pump = Pump.find(params[:id])
    if params[:provider_id]
      begin
      @provider = Provider.find(params[:provider_id])
      @pump.update!(pump_params)
      redirect_to admin_provider_path(@provider)
      rescue ActiveRecord::RecordInvalid => invalid
        flash[:error_messages] = invalid.record.errors.full_messages
        redirect_to edit_admin_provider_pump_path(@provider,@pump)
      end
    else
      begin
      @pump.update!(pump_params)
      redirect_to admin_pumps_path
      rescue ActiveRecord::RecordInvalid => invalid
        flash[:error_messages] = invalid.record.errors.full_messages
        redirect_to edit_admin_pump_path(@pump)
      end
    end
  end

  def destroy
    Pump.destroy(params[:id])
    if params[:provider_id]
      @provider = Provider.find(params[:provider_id])
      redirect_to admin_provider_path(@provider)
    else
      redirect_to admin_pumps_path
    end
  end



  private

  def pump_params
    params.require(:pump).permit(:name,:longitude, :latitude, :location_id, :provider_id)
  end

end

app/controllers/pumps_controller.rb
class PumpsController < ApplicationController
  include PerspectiveSummary
  layout "provider_application"
  before_filter :require_employee_signin

  def index
    @pumps = current_provider.pumps
    js :viz_data => [dispensed_by_pump_for_provider(current_provider), getHubs]
    @total_dispensed = @pumps.reduce(0) { |sum, pump| sum + pump.water_dispensed }
  end

  def show
    @pump = Pump.find(params[:id])
    js :viz_data => [dispensed_by_month(@pump)]
  end
end

app/views/pumps/_list.haml
.table-responsive
  %table#dataTables-example.table.table-striped.table-bordered.table-hover.mt20
    %thead
      %tr
        %th Location Id
        %th Name
        %th Water Pumped
        %th Status
        %th
    %tbody
      - @pumps.each_with_index do |pump, index|
        - index % 2 == 0 ? classes = ["odd","gradeX"] : classes = ["even","gradeC"]
        %tr{:class => classes}
          %td= pump.location_id
          %td= link_to "#{pump.name}", pump_path(pump)
          %td= @total_dispensed
          %td
            .pull-right
              - case pump.status_code
                - when -1
                  %span.label.label-danger Danger
                - when 0
                  %span.label.label-warning Warning
                - when 1
                  %span.label.label-success Ok
          %td
            = link_to '<i class="fa fa-trash fa-fw"></i>'.html_safe, admin_pump_path(pump), method: :delete, data: { confirm: 'Are you sure?' }
            = link_to '<i class="fa fa-pencil fa-fw"></i>'.html_safe, edit_admin_pump_path(pump)
:javascript
  $(document).ready(function() {
      $('#dataTables-example').dataTable();
  });

app/views/pumps/index.haml
.row
.col-lg-12
	%h1.page-header Pumps
.col-lg-12
	= render 'list'
.col-lg-12
	.panel.panel-default
		.panel-heading
			Liters of Water Dispensed By Pump
			.pull-right
		.panel-body
			#chart-container
%h3= "Total liters of water dispensed: #{@total_dispensed}"
.col-lg-12
	.panel.panel-default.mt20
		.panel-heading
			%i.fa.fa-map-marker.fa-fw
			Pumps	
			.pull-right
				.minimize.map-button
					%i.fa.fa-minus.fa-fw
		.panel-body#map.pumps-index
= render 'list'

app/views/pumps/show.haml
.col-lg-12
	%h1.page-header
		= @pump.name
		%small - Pump
.col-lg-12
	%h3.pull-left General information
.col-lg-6
	%table.gen-info
		%col.col-lg-5
		%col.col-lg-5
		%tr
			%th Name
			%td= @pump.name
		%tr
			%th Location ID
			%td= @pump.location_id
.col-lg-6
	%table.gen-info
		%col.col-lg-5
		%col.col-lg-5
		%tr
			%th Longitude
			%td= @pump.longitude
		%tr
			%th Latitude
			%td= @pump.latitude
.col-lg-12
	.panel.panel-default.mt20
		.panel-heading
		.panel-body
			#chart-container
.col-lg-12
	%h3 Total transactions per month
	.table-responsive
		%table#dataTables-example.table.table-basic.table-bordered.table-hover.mt20
			%thead
				%tr
					%th Month
					%th Profit
			%tbody
				%tr.odd.gradeX
					%td May
					%td $ 23.835
				%tr.even.gradeC
					%td June
					%td $ 32.142
.row
.col-lg-12
	%h3 Latest transactions
	.table-responsive
		%table#dataTables-example.table.table-basic.table-bordered.table-hover.mt20
			%thead
				%tr
					%th Transaction ID
					%th Transaction code
					%th Transaction amount
					%th Transaction date
			%tbody
				- @pump.transactions.each do |t|
					%tr
						%td= t.id
						%td= t.transaction_code
						%td= t.amount
						%td= t.transaction_time
.row